#!/usr/bin/python

import cv2

facecascade = cv2.CascadeClassifier('/home/katiechang/Documents/opencv/data/haarcascades/haarcascade_frontalface_default.xml')
vc = cv2.VideoCapture(0)

while True:
    rval, frame = vc.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces = facecascade.detectMultiScale(gray, 1.3, 5)
    for(x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
    cv2.imshow('hi',frame)
    key = cv2.waitKey(20)
    if key == 27:
         break

cv2.destroyAllWindows()

