#!/usr/bin/python

import cv2

frontalfcascade = cv2.CascadeClassifier('/home/katiechang/Documents/opencv/data/haarcascades/haarcascade_frontalface_default.xml')
video = cv2.VideoCapture("/home/katiechang/Documents/Programs/video.mp4")

while True:
    rval,frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces = frontalfcascade.detectMultiScale(gray,scaleFactor=1.1, minNeighbors=15,minSize=(30,30),flags=cv2.CASCADE_SCALE_IMAGE)

    for(x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)

    cv2.imshow("vid", frame)
    key = cv2.waitKey(1)
    if key == 27:
        break
