#!/usr/bin/python

import cv2

frontalfcascade = cv2.CascadeClassifier('/home/katiechang/Documents/opencv/data/haarcascades/haarcascade_frontalface_default.xml')
eyescascade = cv2.CascadeClassifier('/home/katiechang/Documents/opencv/data/haarcascades/haarcascade_eye.xml')
image = cv2.imread("/home/katiechang/Documents/Programs/imagee.jpg")
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
faces = frontalfcascade.detectMultiScale(gray,scaleFactor=1.1, minNeighbors=5,minSize=(10,10),flags=cv2.CASCADE_SCALE_IMAGE)

for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y), (x+w,y+h),(100,0,0),2)
    egray= gray[y:y+h, x:x+w]
    ecolor= image[y:y+h, x:x+w]
    eyes = eyescascade.detectMultiScale(egray)
    for (x2,y2,w2,h2) in eyes:
        cv2.rectangle(ecolor,(x2,y2), (x2+w2,y2+h2),(100,100,0),2)

cv2.imshow("img", image)
cv2.waitKey(0)
