#!/usr/bin/python

#install dlib and imutils

from imutils import face_utils
import numpy as np
import imutils
import dlib
import cv2

image = cv2.imread("/home/katiechang/Documents/Programs/imagee.jpg")
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("/home/katiechang/Documents/Programs/FaceLandmark/shape_predictor_68_face_landmarks.dat")
rects = detector(gray,1)

for (i, rect) in enumerate(rects):
    shape = predictor(gray,rect)
    shape = face_utils.shape_to_np(shape)
    (x,y,w,h) = face_utils.rect_to_bb(rect)
    for (x,y) in shape:
        cv2.circle(image, (x,y), 1, (100, 400, 0), -1)

cv2.imshow("Landmark", image)
cv2.waitKey(0)
